import React, { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Button,
  Box,
  Alert,
  CircularProgress,
  InputAdornment,
  IconButton,
  Typography,
  Divider,
  MenuItem,
  FormControl,
  InputLabel,
  Select,
} from '@mui/material';
import {
  Visibility,
  VisibilityOff,
  Business as BusinessIcon,
} from '@mui/icons-material';
import { toast } from 'react-toastify';
import api from '../../services/api';

/**
 * Register Representative Dialog Component
 * Allows company representatives to register (requires staff approval)
 * 
 * @param {Object} props - Component props
 * @param {boolean} props.open - Dialog open state
 * @param {Function} props.onClose - Function to close dialog
 * @returns {JSX.Element} Registration dialog
 */
const RegisterRepresentative = ({ open, onClose }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
    companyName: '',
    industry: '',
    position: '',
  });

  // Industry options
  const industries = [
    'Technology',
    'Finance',
    'Healthcare',
    'Education',
    'Manufacturing',
    'Retail',
    'Consulting',
    'Engineering',
    'Marketing & Advertising',
    'Media & Entertainment',
    'Telecommunications',
    'Real Estate',
    'Hospitality & Tourism',
    'Transportation & Logistics',
    'Energy & Utilities',
    'Pharmaceuticals',
    'Legal Services',
    'Government & Public Sector',
    'Non-Profit',
    'Other',
  ];

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    setError('');
  };

  const handleClose = () => {
    setFormData({
      name: '',
      email: '',
      password: '',
      confirmPassword: '',
      companyName: '',
      industry: '',
      position: '',
    });
    setError('');
    onClose();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      // Validation
      if (!formData.name || !formData.email || !formData.companyName || !formData.industry || !formData.position) {
        throw new Error('Please fill in all required fields');
      }

      const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailPattern.test(formData.email)) {
        throw new Error('Please enter a valid email address');
      }

      if (formData.password.length < 6) {
        throw new Error('Password must be at least 6 characters long');
      }

      if (formData.password !== formData.confirmPassword) {
        throw new Error('Passwords do not match');
      }

      // Call API (Representative ID will be auto-generated by backend)
      const response = await api.post('/auth/register-representative', {
        name: formData.name,
        email: formData.email,
        password: formData.password,
        companyName: formData.companyName,
        industry: formData.industry,
        position: formData.position,
      });

      toast.success('Registration submitted successfully! Please wait for staff approval.');
      handleClose();

    } catch (err) {
      const errorMessage = err.response?.data?.message || err.message || 'Failed to register';
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog 
      open={open} 
      onClose={handleClose}
      maxWidth="md"
      fullWidth
    >
      <DialogTitle>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <BusinessIcon color="primary" />
          Company Representative Registration
        </Box>
      </DialogTitle>

      <DialogContent>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Register your company to participate in the Internship Placement System.
          Your registration will be reviewed by staff before approval.
        </Typography>

        {error && (
          <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>
            {error}
          </Alert>
        )}

        <Box component="form" onSubmit={handleSubmit}>
          {/* Personal Information */}
          <Typography variant="subtitle1" fontWeight="bold" sx={{ mb: 1, mt: 2 }}>
            Personal Information
          </Typography>
          <Divider sx={{ mb: 2 }} />

          <TextField
            fullWidth
            required
            label="Full Name"
            name="name"
            value={formData.name}
            onChange={handleChange}
            sx={{ mb: 2 }}
          />

          <TextField
            fullWidth
            required
            label="Email"
            name="email"
            type="email"
            value={formData.email}
            onChange={handleChange}
            sx={{ mb: 2 }}
          />

          {/* Company Information */}
          <Typography variant="subtitle1" fontWeight="bold" sx={{ mb: 1, mt: 3 }}>
            Company Information
          </Typography>
          <Divider sx={{ mb: 2 }} />

          <TextField
            fullWidth
            required
            label="Company Name"
            name="companyName"
            value={formData.companyName}
            onChange={handleChange}
            sx={{ mb: 2 }}
          />

          <FormControl fullWidth required sx={{ mb: 2 }}>
            <InputLabel>Industry</InputLabel>
            <Select
              name="industry"
              value={formData.industry}
              onChange={handleChange}
              label="Industry"
            >
              {industries.map((industry) => (
                <MenuItem key={industry} value={industry}>
                  {industry}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <TextField
            fullWidth
            required
            label="Position/Title"
            name="position"
            value={formData.position}
            onChange={handleChange}
            placeholder="e.g., HR Manager, Recruitment Specialist"
            helperText="Your job title or position in the company"
            sx={{ mb: 2 }}
          />

          {/* Password */}
          <Typography variant="subtitle1" fontWeight="bold" sx={{ mb: 1, mt: 3 }}>
            Set Password
          </Typography>
          <Divider sx={{ mb: 2 }} />

          <TextField
            fullWidth
            required
            label="Password"
            name="password"
            type={showPassword ? 'text' : 'password'}
            value={formData.password}
            onChange={handleChange}
            helperText="Minimum 6 characters"
            sx={{ mb: 2 }}
            InputProps={{
              endAdornment: (
                <InputAdornment position="end">
                  <IconButton
                    onClick={() => setShowPassword(!showPassword)}
                    edge="end"
                  >
                    {showPassword ? <VisibilityOff /> : <Visibility />}
                  </IconButton>
                </InputAdornment>
              ),
            }}
          />

          <TextField
            fullWidth
            required
            label="Confirm Password"
            name="confirmPassword"
            type={showConfirmPassword ? 'text' : 'password'}
            value={formData.confirmPassword}
            onChange={handleChange}
            InputProps={{
              endAdornment: (
                <InputAdornment position="end">
                  <IconButton
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    edge="end"
                  >
                    {showConfirmPassword ? <VisibilityOff /> : <Visibility />}
                  </IconButton>
                </InputAdornment>
              ),
            }}
          />
        </Box>
      </DialogContent>

      <DialogActions>
        <Button onClick={handleClose} disabled={loading}>
          Cancel
        </Button>
        <Button
          variant="contained"
          onClick={handleSubmit}
          disabled={loading}
          startIcon={loading && <CircularProgress size={20} />}
        >
          {loading ? 'Submitting...' : 'Register'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default RegisterRepresentative;
